"""Initial migration

Revision ID: bfd001f317e0
Revises: f8fae7de1801
Create Date: 2024-11-18 10:30:19.016677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd001f317e0'
down_revision: Union[str, None] = 'f8fae7de1801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_id'), 'film', ['id'], unique=True)
    op.create_table('Фильмы сегодня',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Фильмы сегодня_id'), 'Фильмы сегодня', ['id'], unique=True)
    op.create_table('film_actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('film_actor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_actor'], ['film.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_actor_id'), 'film_actor', ['id'], unique=True)
    op.create_table('film_foto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('film_foto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_foto'], ['film.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_foto_id'), 'film_foto', ['id'], unique=True)
    op.drop_index('ix_Фильмы_id', table_name='Фильмы')
    op.drop_table('Фильмы')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Фильмы',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.VARCHAR(), nullable=True),
    sa.Column('foto', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Фильмы_id', 'Фильмы', ['id'], unique=1)
    op.drop_index(op.f('ix_film_foto_id'), table_name='film_foto')
    op.drop_table('film_foto')
    op.drop_index(op.f('ix_film_actor_id'), table_name='film_actor')
    op.drop_table('film_actor')
    op.drop_index(op.f('ix_Фильмы сегодня_id'), table_name='Фильмы сегодня')
    op.drop_table('Фильмы сегодня')
    op.drop_index(op.f('ix_film_id'), table_name='film')
    op.drop_table('film')
    # ### end Alembic commands ###
